main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: PLAINTEXT
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: bfarr-rh
    #username: PLAINTEXT
    email: bfarr@redhat.com
    dev_revision: main

  s3:
    bucket:
      name: BUCKETNAME
      region: ap-southeast-1
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false
